hook.Add("Initialize","MMM_M9k_plus_Initkillicons",function()
	if CLIENT and MMM_M9k_IsBaseInstalled then
		local icol = Color(255,255,255)

		killicon.Add("m9k_vp90","vgui/hud/m9k_vp90",icol)
		killicon.Add("m9k_glock18_extclip","vgui/hud/m9k_glock18_extclip",icol)
		killicon.Add("m9k_fnp","vgui/hud/m9k_fnp",icol)
		killicon.Add("m9k_guardian","vgui/hud/m9k_guardian",icol)
		killicon.Add("m9k_ruger","vgui/hud/m9k_ruger",icol)
		killicon.Add("m9k_usps","vgui/hud/m9k_usps",icol)
		killicon.Add("m9k_coltscoped","vgui/hud/m9k_coltscoped",icol)
		killicon.Add("m9k_mr96","vgui/hud/m9k_mr96",icol)
		killicon.Add("m9k_bren_ten","vgui/hud/m9k_bren_ten",icol)

		killicon.Add("m9k_m4a4","vgui/hud/m9k_m4a4",icol)
		killicon.Add("m9k_lr300","vgui/hud/m9k_lr300",icol)
		killicon.Add("m9k_sturmgewehr44","vgui/hud/m9k_sturmgewehr44",icol)
		killicon.Add("m9k_vz58","vgui/hud/m9k_vz58",icol)
		killicon.Add("m9k_fnc","vgui/hud/m9k_fnc",icol)
		killicon.Add("m9k_xm8","vgui/hud/m9k_xm8",icol)
		killicon.Add("m9k_qbz97","vgui/hud/m9k_qbz97",icol)
		killicon.Add("m9k_fw","vgui/hud/m9k_fw",icol)
		killicon.Add("m9k_asg36","vgui/hud/m9k_asg36",icol)
		killicon.Add("m9k_m16a4","vgui/hud/m9k_m16a4",icol)
		killicon.Add("m9k_ak74u","vgui/hud/m9k_ak74u",icol)
		killicon.Add("m9k_ak47sd","vgui/hud/m9k_ak47sd",icol)

		killicon.Add("m9k_ksg","vgui/hud/m9k_ksg",icol)
		killicon.Add("m9k_spas12stock","vgui/hud/m9k_spas12stock",icol)
		killicon.Add("m9k_dragonsbreath","vgui/hud/m9k_dragonsbreath",icol)
		killicon.Add("m9k_serbushorty","vgui/hud/m9k_serbushorty",icol)
		killicon.Add("m9k_fntps","vgui/hud/m9k_fntps",icol)
		killicon.Add("m9k_spas12silenced","vgui/hud/m9k_spas12silenced",icol)
		killicon.Add("m9k_baikal","vgui/hud/m9k_baikal",icol)
		killicon.Add("m9k_m3tactical","vgui/hud/m9k_m3tactical",icol)
	end
end)